export const portfolioData = {
  odyssey: {
    id: 1,
    name: "Odyssey",
    title: "",
    tagline: "",
    overview: "",
    img1: "",
    vision: "",
    quote: "",
    img2: "",
    features: "",
    improve: "",
    tech: [
      "React",
      "NextAuth",
      "TailwindCSS",
      "NextJs",
      "PostgreSQL",
      "Prisma",
    ],
    github: "https://Ibra-Zeno.github.io/odyssey",
    website: "https://was-here.vercel.app/",
    img: "/images/projectPage/odysseyShot.png",
  },
  optima: {
    id: 1,
    name: "Optima",
    title: "",
    tagline: "",
    overview: "",
    img1: "",
    vision: "",
    quote: "",
    img2: "",
    features: "",
    improve: "",
    tech: ["HTML", "TailwindCSS", "JavaScript"],
    github: "https://Ibra-Zeno.github.io/odyssey",
    website: "https://was-here.vercel.app/",
    img: "/images/projectPage/odysseyShot.png",
  },
  ecommerce: {
    id: 1,
    name: "Ecommerce Store",
    title: "",
    tagline: "",
    overview: "",
    img1: "",
    vision: "",
    quote: "",
    img2: "",
    features: "",
    improve: "",
    tech: [
      "React",
      "TypeScript",
      "Stripe",
      "JavaScript",
      "Sanity",
      "TailwindCSS",
      "NextJs",
    ],
    github: "https://Ibra-Zeno.github.io/odyssey",
    website: "https://was-here.vercel.app/",
    img: "/images/projectPage/odysseyShot.png",
  },
  arch: {
    id: 1,
    name: "Architectural Portfolio",
    title: "",
    tagline: "",
    overview: "",
    img1: "",
    vision: "",
    quote: "",
    img2: "",
    features: "",
    improve: "",
    tech: ["NextJS", "React", "TailwindCSS", "popmotion", "FramerMotion"],
    github: "https://Ibra-Zeno.github.io/odyssey",
    website: "https://was-here.vercel.app/",
    img: "/images/projectPage/odysseyShot.png",
  },
  summariser: {
    id: 1,
    name: "AI Summariser",
    title: "",
    tagline: "",
    overview: "",
    img1: "",
    vision: "",
    quote: "",
    img2: "",
    features: "",
    improve: "",
    tech: ["React", "Redux", "JavaScript", "TailwindCSS"],
    github: "https://Ibra-Zeno.github.io/odyssey",
    website: "https://was-here.vercel.app/",
    img: "/images/projectPage/odysseyShot.png",
  },
};

export const projectOrder = [
  "odyssey",
  "optima",
  "ecommerce",
  "arch",
  "summariser",
];
/* 
Title
tagline
Overview
img1
Vision/Foundation
img2
Features
Future Improvements
*/
